version: "3.9"

services:
  systemfailure-deefake-detection-api:
    #image: ${REGISTRY_URl}/${VENDOR}/${APP_IMAGE}:${APP_TAG}
    image: ${VENDOR}/${APP_IMAGE}:${APP_TAG}
    environment:
      - PATH_PREFIX=${PATH_PREFIX}
      - WORKERS=${WORKERS}
      - VIDEO_STROBE=${VIDEO_STROBE}
      - MAX_SEQUENCES=${MAX_SEQUENCES}
      - DOUBLE_RES_CHECK=${DOUBLE_RES_CHECK}
      - FACE_DETECTOR_INPUT_SIZE=${FACE_DETECTOR_INPUT_SIZE}
      - LOG_MAX_SIZE=${LOG_MAX_SIZE}
      - LOG_MAX_FILE=${LOG_MAX_FILE}
    logging:
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
    ports:
      - ${PUBLISH_PORT}:5000
    deploy:
      placement:
        max_replicas_per_node: ${REPL_PER_NODE}
      mode: replicated
      replicas: ${CORE_COUNT}
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
